// src/converters/piral-react-15/src/extension.ts
import { ExtensionSlotProps, compare } from 'piral-core';
import { createElement, Component } from 'react-15';
import { anyPropType } from './mount';

export function createExtension(rootName = 'slot') {
  const React15Extension: any = class extends Component<ExtensionSlotProps> {
    static contextTypes = {
      piral: anyPropType,
    };

    private onRefChange = (element: HTMLElement) => {
      if (element) {
        const { piral } = this.context;
        element.innerHTML = '';
        piral.renderHtmlExtension(element, this.props);
      }
    };

    shouldComponentUpdate(nextProps: ExtensionSlotProps) {
      return !compare(this.props, nextProps);
    }

    render() {
      return createElement(rootName, {
        ref: this.onRefChange,
      });
    }
  };

  return React15Extension;
}

// src/converters/piral-solid/src/extension.ts
import type { PiletApi, ExtensionSlotProps } from 'piral-core';
import type { Component } from 'solid-js';

export function createExtension(api: PiletApi, rootName = 'slot'): Component<ExtensionSlotProps> {
  return props => {
    const element = document.createElement(rootName);
    setTimeout(() => api.renderHtmlExtension(element, props), 0);
    return element as any;
  };
}
