// src/converters/piral-react/src/types.ts
import type { ForeignComponent, ExtensionSlotProps } from 'piral-core';
import type { Component, ComponentType } from 'react';

declare module 'piral-core/lib/types/custom' {
  interface PiletCustomApi extends PiletReactApi {}

  interface PiralCustomComponentConverters<TProps> {
    react(component: ReactComponent<TProps>): ForeignComponent<TProps>;
  }
}

export interface ReactComponent<TProps> {
  /**
   * The component root.
   */
  root: ComponentType<TProps>;
  /**
   * The type of the React 16+ component.
   */
  type: 'react';
}

/**
 * Defines the provided set of Pilet API extensions from the React 16+ plugin.
 */
export interface PiletReactApi {
  /**
   * Wraps an React 16+ component for use in Piral.
   * @param component The component root.
   * @returns The Piral React 16+ component.
   */
  fromReact<TProps>(component: ComponentType<TProps>): ReactComponent<TProps>;
  /**
   * React 16+ component for displaying extensions of the given name.
   */
  ReactExtension: Component<ExtensionSlotProps>;
}

// src/converters/piral-solid/src/types.ts
import { ForeignComponent, ExtensionSlotProps } from 'piral-core';
import { Component } from 'solid-js';

declare module 'piral-core/lib/types/custom' {
  interface PiletCustomApi extends PiletSolidApi {}

  interface PiralCustomComponentConverters<TProps> {
    solid(component: SolidComponent<TProps>): ForeignComponent<TProps>;
  }
}

export interface SolidComponent<TProps> {
  /**
   * The component root.
   */
  root: Component<TProps>;
  /**
   * The type of the Solid component.
   */
  type: 'solid';
}

/**
 * Defines the provided set of Solid Pilet API extensions.
 */
export interface PiletSolidApi {
  /**
   * Wraps a Solid component for use in Piral.
   * @param component The name of the root component.
   * @returns The Piral Solid component.
   */
  fromSolid<TProps>(root: Component<TProps>): SolidComponent<TProps>;
  /**
   * Gets the name of the Solid extension.
   */
  SolidExtension: Component<ExtensionSlotProps>;
}
