// src/converters/piral-react-15/src/types.ts
import { ForeignComponent, ExtensionSlotProps } from 'piral-core';
import { Component, ComponentType } from 'react-15';

declare module 'piral-core/lib/types/custom' {
  interface PiletCustomApi extends PiletReact15Api {}

  interface PiralCustomComponentConverters<TProps> {
    react15(component: React15Component<TProps>): ForeignComponent<TProps>;
  }
}

export interface React15Component<TProps> {
  /**
   * The component root.
   */
  root: ComponentType<TProps>;
  /**
   * The type of the React 15.x component.
   */
  type: 'react15';
}

/**
 * Defines the provided set of Pilet API extensions from the React 15.x plugin.
 */
export interface PiletReact15Api {
  /**
   * Wraps an React 15.x component for use in Piral.
   * @param component The component root.
   * @returns The Piral React 15.x component.
   */
  fromReact15<TProps>(component: ComponentType<TProps>): React15Component<TProps>;
  /**
   * React 15.x component for displaying extensions of the given name.
   */
  React15Extension: Component<ExtensionSlotProps>;
}

// src/converters/piral-solid/src/types.ts
import { ForeignComponent, ExtensionSlotProps } from 'piral-core';
import { Component } from 'solid-js';

declare module 'piral-core/lib/types/custom' {
  interface PiletCustomApi extends PiletSolidApi {}

  interface PiralCustomComponentConverters<TProps> {
    solid(component: SolidComponent<TProps>): ForeignComponent<TProps>;
  }
}

export interface SolidComponent<TProps> {
  /**
   * The component root.
   */
  root: Component<TProps>;
  /**
   * The type of the Solid component.
   */
  type: 'solid';
}

/**
 * Defines the provided set of Solid Pilet API extensions.
 */
export interface PiletSolidApi {
  /**
   * Wraps a Solid component for use in Piral.
   * @param component The name of the root component.
   * @returns The Piral Solid component.
   */
  fromSolid<TProps>(root: Component<TProps>): SolidComponent<TProps>;
  /**
   * Gets the name of the Solid extension.
   */
  SolidExtension: Component<ExtensionSlotProps>;
}
